# Generated by Django 6.0.2 on 2026-03-09 09:10

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('hostel_type', models.CharField(choices=[('mixed', 'Mixed'), ('male', 'Male Only'), ('female', 'Female Only')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('campus', models.CharField(choices=[('main', 'Main Campus (Arts & Social Sciences)'), ('east', 'East Campus (Science & Technology)'), ('west', 'West Campus (Health Sciences)'), ('north', 'North Campus (Education)'), ('south', 'South Campus (Business & Economics)'), ('central', 'Central Campus (Agriculture)')], db_index=True, max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('total_rooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('occupied_rooms', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_per_semester', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UG')),
                ('alternative_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='UG')),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(help_text='The landlord who owns this hostel', limit_choices_to={'user_type': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.facility')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='hostels.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='HostelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hostel_images/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hostels.hostel')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hostels.hostel')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['campus', 'is_verified'], name='hostels_hos_campus_8c00e3_idx'),
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['price_per_semester'], name='hostels_hos_price_p_d852c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hostelfacility',
            unique_together={('hostel', 'facility')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('hostel', 'student')},
        ),
    ]
